spring:
  application:
    name: cookpedia
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  output:
    ansi:
      enabled: always
  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE