server:
  port: ${SERVER_PORT:18080}
spring:
  data:
    mongodb:
      host: 192.168.50.20
      port: 27017
      database: cookpedia
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    distribution:
      sla:
        http:
          server:
            requests: 50ms,100ms,200ms,300ms,500ms,1s
    tags:
      application: app-cookpedia-api